services:
  db:
    image: mysql:8.0
    container_name: api_tweets
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecret
      - MYSQL_DATABASE=api_tweets
    volumes:
      - ./mysql:/var/lib/mysql